import bcrypt from "bcryptjs";

const data = {
  users: [
    {
      name: "Yoko",
      email: "adminyoko@example.com",
      password: bcrypt.hashSync("7575", 8),
      isAdmin: true,
    },
    {
      name: "Toto",
      email: "user@example.com",
      password: bcrypt.hashSync("1234", 8),
      isAdmin: false,
    },
  ],
  products: [
    {
      name: "Ipple smartphone reboot",
      category: "Phones",
      image: "/images/p1.jpg",
      price: 120,
      countInStock: 10,
      brand: "Ipple",
      rating: 4.5,
      numReviews: 10,
      description: "Ipple smartphone reconditioned",
    },
    {
      name: "Huowei smartphone reboot",
      category: "Phones",
      image: "/images/p2.jpg",
      price: 80,
      countInStock: 20,
      brand: "Huowei",
      rating: 4.0,
      numReviews: 5,
      description: "Huowei smartphone reconditioned",
    },
    {
      name: " Samsang smartphone reboot",
      category: "Phones",
      image: "/images/p3.jpg",
      price: 100,
      countInStock: 1,
      brand: "Samsang",
      rating: 4.8,
      numReviews: 17,
      description: "Samsang smartphone reconditioned",
    },
    {
      name: " Ipple laptop reboot",
      category: "Laptop",
      image: "/images/p4.jpg",
      price: 930,
      countInStock: 0,
      brand: "Ipple",
      rating: 4.5,
      numReviews: 23,
      description: "Ipple laptop reconditioned",
    },
    {
      name: "Dull laptop reboot",
      category: "Laptop",
      image: "/images/p5.jpg",
      price: 720,
      countInStock: 3,
      brand: "Dull",
      rating: 4.5,
      numReviews: 10,
      description: "Dull laptop reconditioned",
    },
    {
      name: "MSA laptop reboot",
      category: "Laptop",
      image: "/images/p6.jpg",
      price: 890,
      countInStock: 2,
      brand: "MSA",
      rating: 4.5,
      numReviews: 10,
      description: "MSA laptop reconditioned",
    },
  ],
};

export default data;
