const data = {
  products: [
    {
      _id: "1",
      name: "Ipple smartphone reboot",
      category: "Phones",
      image: "/images/p1.jpg",
      price: 120,
      countInStoch: 10,
      brand: "Ipple",
      rating: 4.5,
      numReviews: 10,
      description: "Ipple smartphone reconditioned",
    },
    {
      _id: "2",
      name: "Huowei smartphone reboot",
      category: "Phones",
      image: "/images/p2.jpg",
      price: 80,
      countInStoch: 20,
      brand: "Huowei",
      rating: 4.0,
      numReviews: 5,
      description: "Huowei smartphone reconditioned",
    },
    {
      _id: "3",
      name: " Samsang smartphone reboot",
      category: "Phones",
      image: "/images/p3.jpg",
      price: 100,
      countInStoch: 1,
      brand: "Samsang",
      rating: 4.8,
      numReviews: 17,
      description: "Samsang smartphone reconditioned",
    },
    {
      _id: "4",
      name: " Ipple laptop reboot",
      category: "Laptop",
      image: "/images/p4.jpg",
      price: 930,
      countInStoch: 0,
      brand: "Ipple",
      rating: 4.5,
      numReviews: 23,
      description: "Ipple laptop reconditioned",
    },
    {
      _id: "5",
      name: "Dull laptop reboot",
      category: "Laptop",
      image: "/images/p5.jpg",
      price: 720,
      countInStoch: 3,
      brand: "Dull",
      rating: 4.5,
      numReviews: 10,
      description: "Dull laptop reconditioned",
    },
    {
      _id: "6",
      name: "MSA laptop reboot",
      category: "Laptop",
      image: "/images/p6.jpg",
      price: 890,
      countInStoch: 2,
      brand: "MSA",
      rating: 4.5,
      numReviews: 10,
      description: "MSA laptop reconditioned",
    },
  ],
};

export default data;
